version: '3.8'

services:
  server:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@server-db:5432/server_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@server-db:5432/server_test
      - SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET
    depends_on:
      - server-db

  server-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  admin-react:
    build: 
      context: ./admin-react-app
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./admin-react-app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_BACKEND_BASE_URL=$VITE_BACKEND_BASE_URL
    ports:
      - 3000:3000
      - 3010:3010
