version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3 # Invoke the Heroku orb

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main

  test:
    jobs:
      - build

  lint:
    jobs:
      - lint

jobs:
  build:
    machine: true
    working_directory: ~/src

    steps:
      - checkout
      - run: touch .env # env files have to exist for docker-compose to work
      - run: docker-compose exec server aerich init -t app.db.TORTOISE_ORM
      - run: docker-compose exec server aerich init-db
      - run: docker-compose exec server python -m pytest

  lint:
    machine: true
    working_directory: ~/src

    steps:
      - checkout
      - run: touch ./server/.env
      - run: docker-compose run server npm run lint
